packages:
  - api/
  - expo/
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": next
  "@trpc/react-query": next
  "@trpc/server": next
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: rc
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
